#!/bin/bash

# convert "$1" -trim \( +clone -background grey25 -shadow 70x25+3+20 \) +swap -background transparent -layers merge +repage "$1-shadow.png"
convert "$1" -trim \( +clone -background grey25 -shadow 25x7+0+5 \) +swap -background transparent -layers merge +repage "$1-shadow.png"
