#!/usr/bin/env bash


backup() {
  bdir=../imgrename-backup-$(date +%d%m%y)
  [ -d $bdir ] && rm -rf "$bdir/*" || mkdir "$bdir"

  cp -r * "$bdir"
}

rename() {
  tdir=../dir-temp
  tdir_noimg=../dir-temp-noimg
  mkdir "$tdir" "$tdir_noimg"

  num=1
  for file in *; do
    # Get file extension
    ext=$(file -b "$file")
    ext=$(echo ${ext%% *} | tr '[:upper:]' '[:lower:]')

    # If file has png, jpg or jpeg extension, rename the file
    if [[ $ext = 'png' || $ext = 'jpg' || $ext = 'jpeg' ]]; then
      mv -- "$file" "$tdir/image$num.$ext"
    else
      # move the file elsewhere, then move back
      mv -- "$file" "$tdir_noimg"
    fi
    ((num++))
  done

  # Replace the old images and clean up the temp directories
  rm -rf *
  mv $tdir/* .
  mv $tdir_noimg/* .
  rm -rf "$tdir" "$tdir_noimg"
}

confirm() {
  ls -a
  read -p 'Do you want to rename all images? (y/n) ' answer
  case $answer in
    y|Y) return 0;;
    n|N) exit 0;;
    *) echo 'invalid option'; confirm;;
  esac
}

confirm
if [ -z "$1" ]; then
  rename
else
  case $1 in
    -b|--backup ) backup; rename;;
    * ) echo "$0: invalid option -- '$1'";;
  esac
fi
