#!/usr/bin/env bash

backup() {
  bdir=../imgrename-backup-$(date +%d%m%y)
  if [ -d $bdir ]; then
    rm -rf $bdir/*
  else
    mkdir $bdir
  fi
  cp -r * $bdir
}

# Si el nombre del archivo tiene espacios, la extension da 'cannot cannot' 😞 
rename() {
  tdir=../temp-imgrename
  mkdir $tdir
  num=1
  for file in *; do
    ext=$(file -b $file)
    mv -- $file $tdir/image$num.$(echo ${ext%% *} | tr '[:upper:]' '[:lower:]')
    ((num++))
  done
  rm -rf *
  mv $tdir/* .
  rm -rf $tdir
}

confirm() {
  ls -a
  read -p 'Do you want to rename all images? (y/n) ' answer
  case $answer in
    y|Y) return 0;;
    n|N) exit 0;;
    *) echo invalid option; confirm;;
  esac
}

confirm
if [ -z "$1" ]; then
  rename
else
  case $1 in
    -b|--backup ) backup; rename;;
    * ) echo "$0: invalid option -- '$1'";;
  esac
fi
