#!/usr/bin/env bash

workspaces() {
  cur="$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')"; ((cur++))
  echo "$cur"
}

memused() {
  free -h | awk '{print $3}' | sort -gr | head -1
}

cpuload() {
  cat <(grep 'cpu ' /proc/stat) <(sleep 1 && grep 'cpu ' /proc/stat) |
    awk -v RS="" '{printf "%.2f%\n", ($13-$2+$15-$4)*100/($13-$2+$15-$4+$16-$5)}'
}

volume() {
  amixer get Master | sed -n 'N;s/^.*\[\([0-9]\+%\).*$/\1/p'
}

clock() {
  date '+%a, %B %d %H:%M'
}

output=""
output="${output} ws: $(workspaces) ";
output="${output} | mem: $(memused)";
output="${output} | cpu: $(cpuload)";
output="${output} | vol: $(volume)";
output="${output} | $(clock)"
    
notify-send "$output"
