#!/usr/bin/env bash

ac=(Shutdown Lock Reboot Suspend)

opt=$(printf "${ac[0]}\n${ac[1]}\n${ac[2]}\n${ac[3]}" | rofi -dmenu -i)

case $opt in
  ${ac[0]}) systemctl poweroff -i       ;;
  ${ac[1]}) betterlockscreen -l dimblur ;;
  ${ac[2]}) systemctl reboot -i         ;;
  ${ac[3]}) systemctl suspend -i        ;;
esac
