#!/usr/bin/env bash

option1="Shutdown"
option2="Lock"
option3="Reboot"
option4="Suspend"

list="$option1\n$option2\n$option3\n$option4"

opt=$(
  echo -e $list |
  rofi -dmenu -config ~/.config/rofi/powermenu.rasi \
  -location 3 -xoffset -15 -yoffset 40 -lines 4 -i
)

case $opt in
  $option1) systemctl poweroff -i;;
  $option2) betterlockscreen -l dimblur;;
  $option3) systemctl reboot -i;;
  $option4) systemctl suspend -i;;
esac
