#!/usr/bin/env bash

DIR=$HOME/pictures/Screenshots
NAME=$(date +%Y%m%d_%H%M%S)

opt1="Whole screen"
opt2="Currently focused window"
opt3="Select screen section"

list="$opt1\n$opt2\n$opt3"

notify() {
  notify-send "Screenshot ($NAME.png) saved at $DIR"
}

menu() {
  choice=$(echo -e $list | rofi -dmenu -lines 3 -i)
  case $choice in
    $opt1) 
      scrot -d 1 $DIR/$NAME.png
      notify
      ;;
    $opt2) 
      scrot -d 1 -u $DIR/$NAME.png
      notify
      ;;
    $opt3) 
      scrot -s $DIR/$NAME.png
      notify
      ;;
  esac
}

while [[ $# -gt 0 ]]; do
  case $1 in
    -f)
      scrot -d 1 $DIR/$NAME.png
      notify
      exit 0;
      ;;
    *)
      echo "Unknown argument: $1"
      exit 1
      ;;
  esac
done

menu
