#!/usr/bin/env bash

DIR=$HOME/Pictures/Screenshots
NAME=$(date +%Y%m%d_%H%M%S)

option1=" Whole screen"
option2=" Currently focused window"
option3=" Select screen section"
list="$option1\n$option2\n$option3"

notification() {
  notify-send "Screenshot ($NAME.png) saved at $DIR"
}

menu() {
  choice=$(
    echo -e $list |
    rofi -dmenu -config ~/.config/rofi/scrot.rasi \
    -location 3 -xoffset -15 -yoffset 15 -lines 3
  )
  case $choice in
    $option1) 
      scrot -d 1 $DIR/$NAME.png
      ;;
    $option2) 
      scrot -d 1 -u $DIR/$NAME.png
      ;;
    $option3) 
      scrot -s $DIR/$NAME.png
      ;;
  esac
  notification
}

while [[ $# -gt 0 ]]; do
  case $1 in
    -f)
      scrot -d 1 $DIR/$NAME.png
      notification
      exit 0;
      ;;
    *)
      echo "Unknown argument: $1"
      exit 1
      ;;
  esac
done

menu
