#!/usr/bin/env bash

[ -z $1 ]     && printf "error: no arg provided"    && exit 1
[ -d $1 ]     && printf "error: $1 is a directory"  && exit 1
[[ ! -f $1 ]] && printf "error: file $1 not found"  && exit 1

curl -F "file=@$1" https://0x0.st
